# Generated by Django 2.2.2 on 2019-12-07 05:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('end_of_period', models.DateTimeField(null=True)),
                ('loan_number', models.CharField(max_length=100)),
                ('borrower', models.CharField(max_length=100, null=True)),
                ('guarantor', models.CharField(max_length=100)),
                ('loan_type', models.CharField(max_length=100)),
                ('loan_status', models.CharField(max_length=100)),
                ('interest_rate', models.FloatField(null=True)),
                ('currency_of_commitment', models.CharField(max_length=100)),
                ('original_principal_amount', models.FloatField(null=True)),
                ('cancelled_amount', models.FloatField(null=True)),
                ('undisbursed_amount', models.FloatField(null=True)),
                ('disbursed_amount', models.FloatField(null=True)),
                ('repaid_to_ibrd', models.FloatField(null=True)),
                ('due_to_ibrd', models.FloatField(null=True)),
                ('exhange_adjustment', models.FloatField(null=True)),
                ('borrower_obligation', models.FloatField(null=True)),
                ('sold_third_party', models.FloatField(null=True)),
                ('repaid_third_party', models.FloatField(null=True)),
                ('due_third_party', models.FloatField(null=True)),
                ('loans_held', models.FloatField(null=True)),
                ('first_repayment_date', models.DateTimeField(null=True)),
                ('last_repayment_date', models.DateTimeField(null=True)),
                ('agreement_signing_date', models.DateTimeField(null=True)),
                ('board_approval_date', models.DateTimeField(null=True)),
                ('most_recent_effective_date', models.DateTimeField(null=True)),
                ('most_recent_closed_date', models.DateTimeField(null=True)),
                ('last_disbursement_date', models.DateTimeField(null=True)),
                ('country_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_country', to='datacollection.Country')),
                ('guarantor_country_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_guarantor_country', to='datacollection.Country')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datacollection.Project')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datacollection.Region')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
    ]
