# Generated by Django 2.2.2 on 2019-12-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0002_auto_20191207_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='most_recent_closed_date',
            new_name='closed_date_most_recent',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='most_recent_effective_date',
            new_name='effective_date_most_recent',
        ),
    ]
