# Generated by Django 2.2.2 on 2019-12-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0003_auto_20191207_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='agreement_signing_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='board_approval_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='closed_date_most_recent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='effective_date_most_recent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='first_repayment_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='last_disbursement_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='last_repayment_date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
