# Generated by Django 2.2.2 on 2019-12-08 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0004_auto_20191207_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='exhange_adjustment',
            new_name='exchange_adjustment',
        ),
    ]
