# Generated by Django 2.2.2 on 2019-12-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0005_auto_20191208_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='due_third_party',
            new_name='due_3rd_party',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='repaid_third_party',
            new_name='repaid_3rd_party',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='sold_third_party',
            new_name='sold_3rd_party',
        ),
    ]
